### ISSUE TITLE
Implement Windows.ApplicationModel.Package 

### ISSUE THREAD

**Issue by jamesmcroft** [XPlat-Apps/XPlat-Windows-APIs#36]
This API will be used to supply information about the application package. 

As a minimum, it should contain:
- Id, the ID of the package.
- InstalledLocation, the StorageFolder location where the package is installed.
- DisplayName, the name of the package.
- PublisherDisplayName, the name of the package publisher.
- Description, the description of the package.

**Comment by tom-made** [comment]
I've updated the tags on this tracking item. I'll try and see if we can look at finishing off the bits for iOS.

**Comment by jamesmcroft** [comment]
@tom-made I think I might be able to piece most of it together with documentation on the iOS side. It looks like a lot of the information can be extracted from the main NSBundle.

**Comment by tom-made** [comment]
@jamesmcroft I believe this is closed off now with the last PR!
