### ISSUE TITLE
NuGet package icon is missing

### ISSUE THREAD

**Issue by tom-made** [XPlat-Apps/XPlat-Windows-APIs#53]
**Which package(s) and version of XPlat are you using?**
All packages on latest release

**Repro steps**
Using the NuGet package manager in Visual Studio or viewing the [XPlat NuGet packages on NuGet.org](https://www.nuget.org/packages/XPlat.Storage/), the icon for the packages is no longer displayed.

Instead, the package is using the default package icon for NuGet.

**Expected behavior**
The XPlat Windows API logo should be displayed for all packages.

**Comment by jamesmcroft** [comment]
Believe this is fixed now, will close off. Apologies!
