### ISSUE TITLE
Windows CoreDispatcher only supports the CoreApplication.MainView.CoreWindow.Dispatcher

### ISSUE THREAD

**Issue by jamesmcroft** [XPlat-Apps/XPlat-Windows-APIs#60]
**Which package(s) and version of XPlat are you using?**
1.5 + 1.6-alpha

**Which platform is the issue related to?**
* [x] Windows (UWP)
* [ ] Xamarin.Android
* [ ] Xamarin.iOS
* [ ] .NET (common)

**Repro steps**
A clear and concise description of what the bug is and how it can be reproduced.

There is no way to initialize an XPlat CoreDispatcher instance for Windows using a Windows CoreDispatcher instance.

**Expected behavior**
A clear and concise description of what you expected to happen (or code).

There should be another constructor for providing an instance.

**Comment by tom-made** [comment]
Thanks for the changes.
