### ISSUE TITLE
[Bug] - Cannot build and deploy API test applications

### ISSUE THREAD

**Issue by jamesmcroft** [XPlat-Apps/XPlat-Windows-APIs#64]
## What type of issue report is this?
> Please check one or more that apply

- [x] Bug
- [ ] Regression
- [ ] Question/support
- [ ] Other (include details)

## Which packages are you using?
> Please provide the packages and versions affects

Unrelated to packages and versions.

## What is the current behaviour?
> Please describe the current behaviour with repro steps

When pulling the source code down, attempting to build the Sample application results in build errors where the error is related to missing build artifacts for projects which otherwise build successfully.

The issue appears to be related to the custom platform-specific csproj logic in the .NET Standard projects.

## What is the expected behaviour?
> Please describe the expected behaviour

The API sample applications should build successfully and run on devices.

## What platforms does this affect?
> Please check one or more that apply

- [x] Windows (UWP)
- [x] Xamarin.Android
- [x] Xamarin.iOS
- [ ] Xamarin.Forms

**Comment by tom-made** [comment]
Fixed!
