### ISSUE TITLE
[Bug] - Unable to add files from cloud services

### ISSUE THREAD

**Issue by Tarc94** [XPlat-Apps/XPlat-Windows-APIs#66]
## What type of issue report is this?
> Please check one or more that apply

- [x] Bug
- [ ] Regression
- [ ] Question/support
- [ ] Other (include details)

## Which packages are you using?
> Version 1.5.19036.3

## What is the current behaviour?
> When I go to open a file from Google Drive it won't return the item correctly.

## What is the expected behaviour?
> When I open a file from Google Drive the item should return correctly.

## What platforms does this affect?
> Please check one or more that apply

- [ ] Windows (UWP)
- [x] Xamarin.Android
- [ ] Xamarin.iOS
- [ ] Xamarin.Forms

**Comment by jamesmcroft** [comment]
Work on this bug was completed on PR #67, closing this off.

Fix will be made available in 1.6 release
