### ISSUE TITLE
[Feature] Use Android Application.Context as default

### ISSUE THREAD

**Issue by jamesmcroft** [XPlat-Apps/XPlat-Windows-APIs#73]
## Description

Currently, there are Android components in the XPlat Windows APIs which require the developer to either pass a Context via a constructor or set a Context property. 

It would be useful to provide a default using the Application.Context, while still allowing the ability to set one.

## How will this benefit you and others?

This will make it easier to adopt certain components where Context is a requirement.

**Comment by wilsonvargas** [comment]
Pls check my PR #76

**Comment by jamesmcroft** [comment]
Work completed for this. Closing off
